# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Run tests with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  unit-test:
    runs-on: [ubuntu-latest, windows-latest, macos-latest]
    name: Run unit tests
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Install the dependencies
      working-directory: .
      run: mvn clean install -DskipTests=true
    - name: Run the tests
      working-directory: .
      run: mvn test
